### ISSUE TITLE
Export multiple images

### ISSUE THREAD

**Issue by richfitz** [richfitz/stevedore#8]
I don't think this is very high value but it does not work as advertised:

```
dyn1212-83:stevedore rich$ curl --verbose --unix-socket /var/run/docker.sock 'http://localhost/v1.29/images/get?names=hello-world:latest,alpine:latest'  > /dev/null
*   Trying /var/run/docker.sock...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (/Users/rich/Library/Containers/com.docker.doc) port 80 (#0)
> GET /v1.29/images/get?names=hello-world:latest,alpine:latest HTTP/1.1
> Host: localhost
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.34
< Content-Length: 39
< Content-Type: application/json
< Date: Fri, 09 Feb 2018 08:50:02 GMT
< Docker-Experimental: true
< Ostype: linux
< Server: Docker/17.11.0-ce-rc2 (linux)
< 
{ [39 bytes data]
* Curl_http_done: called premature == 0
100    39  100    39    0     0  10430      0 --:--:-- --:--:-- --:--:-- 13000
* Connection #0 to host localhost left intact
```

but the spec says

```
      parameters:
        - name: "names"
          in: "query"
          description: "Image names to filter by"
          type: "array"
          items:
            type: "string"
```

See also: https://docs.docker.com/engine/api/v1.29/#operation/ImageGetAll

Urlencoding the `,` (as `%2C`) does not help, nor does changing the presence of the tag, or encoding `:` as `%3A`
